// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdTsFSmDqdDRqkzyZKUG-MNaqRxzCrm8',
    appId: '1:820949642317:web:50ba1ef1a011346b140004',
    messagingSenderId: '820949642317',
    projectId: 'curiosityclash-86972',
    authDomain: 'curiosityclash-86972.firebaseapp.com',
    storageBucket: 'curiosityclash-86972.firebasestorage.app',
    measurementId: 'G-YVXTHTHQ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqkc_rNDXljCkrKYK9PlqoaGx_vlwsuc',
    appId: '1:820949642317:android:b6016e583fa541c3140004',
    messagingSenderId: '820949642317',
    projectId: 'curiosityclash-86972',
    storageBucket: 'curiosityclash-86972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALCL6STaWy9br06xD3XCl3_ZGVdEPEUNI',
    appId: '1:820949642317:ios:1561a3f42b3dca14140004',
    messagingSenderId: '820949642317',
    projectId: 'curiosityclash-86972',
    storageBucket: 'curiosityclash-86972.firebasestorage.app',
    iosBundleId: 'com.feri.curiosityclash.curiosityclash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALCL6STaWy9br06xD3XCl3_ZGVdEPEUNI',
    appId: '1:820949642317:ios:1561a3f42b3dca14140004',
    messagingSenderId: '820949642317',
    projectId: 'curiosityclash-86972',
    storageBucket: 'curiosityclash-86972.firebasestorage.app',
    iosBundleId: 'com.feri.curiosityclash.curiosityclash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcdTsFSmDqdDRqkzyZKUG-MNaqRxzCrm8',
    appId: '1:820949642317:web:fd1b61f7a7cb46e0140004',
    messagingSenderId: '820949642317',
    projectId: 'curiosityclash-86972',
    authDomain: 'curiosityclash-86972.firebaseapp.com',
    storageBucket: 'curiosityclash-86972.firebasestorage.app',
    measurementId: 'G-S85KS5LPP7',
  );
}
